
version: '3.4'

services:
  database:
    image: postgres:14
    restart: always
    ports:
      - 5433:5432
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: abc123
      POSTGRES_DB: quasar
  wildfly:
    build: .
    restart: always
    links: 
      - database
    ports:
      - 8080:8080
      - 8081:9990
      - 8082:8443
